#!/bin/bash
os=$(uname)
# args="--no-window-system --no-init-file --load $HOME/.magit/init.el"
INIT= <<EOF
EOF
args='--no-window-system --eval (open-magit)'
prefix=
if [ "$#" -eq 1 ]; then
    cd $1
fi

if [ "$#" -eq 2 ]; then
    cd $1
    prefix="env SHA=$2"
fi

git rev-parse --is-inside-work-tree > /dev/null && if [ $os == "Darwin" ]; then
  $prefix $(which emacsclient) $args
else
  $prefix emacsclient $args
fi
